using Postgrest.Attributes;
using Postgrest.Models;

namespace TennisRD.Dtos;

public class BaseModelApp : BaseModel
{
    [PrimaryKey("id", false)] // Key is Autogenerated
    public int Id { get; set; }
}